"""add user

Revision ID: 006730583799
Revises: 50172485773a
Create Date: 2026-10-08 00:09:13.727486

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import backend.core.database

# revision identifiers, used by Alembic.
revision: str = "006730583799"
down_revision: Union[str, Sequence[str], None] = "50172485773a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
